### ISSUE TITLE
Clpeak issues (CUDA compilation takes forever && CPU errors)

### ISSUE THREAD

**Issue by oscarbg** [pocl/pocl#522] opened 2017-09-03 06:59 UTC
Hi,
I expected CLpeak to work (https://github.com/krrishnarraj/clpeak) with POCL but seems no..
on CPU:
```
Platform: Portable Computing Language
  Device: pthread-Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
    Driver version  : 0.15-pre (Linux x64)
    Compute units   : 4
    Clock frequency : 4200 MHz

    Global memory bandwidth (GBPS)
      float   : clEnqueueNDRangeKernel (-63)
      Tests skipped

    Single-precision compute (GFLOPS)
clCreateBuffer (-61)
      Tests skipped

    No half precision support! Skipped

    Double-precision compute (GFLOPS)
clCreateBuffer (-61)
      Tests skipped

    Integer compute (GIOPS)
clCreateBuffer (-61)
      Tests skipped

    Transfer bandwidth (GBPS)
      enqueueWriteBuffer         : 0.00
      enqueueReadBuffer          : 0.00
      enqueueMapBuffer(for read) : 0.00
        memcpy from mapped ptr   : inf
      enqueueUnmap(after write)  : 0.00
        memcpy to mapped ptr     : inf

    Kernel launch latency : 2.92 us

```
on CPU errors like clCreateBuffer (-61  CL_INVALID_BUFFER_SIZE  ) clEnqueueNDRangeKernel (-63 CL_INVALID_GLOBAL_WORK_SIZE ) 
avoid most tests working which should be interesting to see if it's generating correct AVX fma instructions and vectorizing correctly..

on GPU 

```
  Device: GeForce GTX 970
    Driver version  : 0.15-pre (Linux x64)
    Compute units   : 13
    Clock frequency : 1253 MHz
```
is stuck here and memory of the process goes growing up and up and process uses CPU a lot so seems may be wants to unroll a gigantic loop of FMAs and either CUDA JIT compiler or LLVM NVPTX gets using full CPU usage for minutes without results..
as said maybe good POCL CUDA support for CLpeak for main reasons:

*Check there are no bottlenecks and gets close to GPU peak performance
*fma/mads are being generated correctly
*large loops don't get unrolled keeping kernel compilation taking infinite time..

**Comment by franz** [comment] 2017-09-03 08:02
clpeak with CPU device (pocl master, LLVM 4) seems to work on my laptop:

```
Platform: Portable Computing Language
  Device: pthread-Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz
    Driver version  : 0.15-pre (Linux x64)
    Compute units   : 4
    Clock frequency : 2501 MHz

    Global memory bandwidth (GBPS)
      float   : 12.23
      float2  : 13.83
      float4  : 12.26
      float8  : 14.03
      float16 : 12.77

    Single-precision compute (GFLOPS)
      float   : 23.28
      float2  : 46.38
      float4  : 23.38
      float8  : 24.36
      float16 : 25.53

    No half precision support! Skipped

    Double-precision compute (GFLOPS)
      double   : 11.79
      double2  : 23.25
      double4  : 11.94
      double8  : 12.09
      double16 : 12.80

    Transfer bandwidth (GBPS)
      enqueueWriteBuffer         : 9.07
      enqueueReadBuffer          : 6.70
      enqueueMapBuffer(for read) : 10110.56
        memcpy from mapped ptr   : 6.68
      enqueueUnmap(after write)  : 20808.95
        memcpy to mapped ptr     : 6.82
```

... though it's true some compilation takes forever. Can't speak for CUDA, but for CPU, either something on your system is borked, pocl miscompiled, or the way you launch clpeak+pocl is wrong. Or LLVM doesn't recognize your CPU. Try running `POCL_DEBUG=1 ./clpeak` might give some useful error messages.

**Comment by oscarbg** [comment] 2017-09-03 09:13
it compiles BC for skylake architecture so seems CPU is recognized after all..
recompiled uing LLVM/Clang 5.0rc3 from (http://prereleases.llvm.org/5.0.0/rc3/clang+llvm-5.0.0-rc3-x86_64-linux-gnu-debian8.tar.xz) and run with POCL_DEBUG=1

```
latform: Portable Computing Language
[2017-08-03 09:06:56.492870898]POCL: in fn cl_int pocl_cuda_init(unsigned int, cl_device_id, const char *) at line 261:
  |   GENERAL |  [CUDA] GPU architecture = sm_52
  Device: pthread-Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
    Driver version  : 0.15-pre (Linux x64)
    Compute units   : 4
    Clock frequency : 4200 MHz
[2017-08-03 09:06:56.543650026]POCL: in fn cl_int compile_and_link_program(int, int, cl_program, cl_uint, const cl_device_id *, const char *, cl_uint, const cl_program *, const char **, cl_uint, const cl_program *, void (*)(cl_program, void *), void *) at line 485:
  |   GENERAL |  building program with options -cl-mad-enable
[2017-08-03 09:06:56.543655908]POCL: in fn cl_int compile_and_link_program(int, int, cl_program, cl_uint, const cl_device_id *, const char *, cl_uint, const cl_program *, const char **, cl_uint, const cl_program *, void (*)(cl_program, void *), void *) at line 531:
  |   GENERAL |  building from sources for device 0
[2017-08-03 09:06:57.913873415]POCL: in fn cl_command_queue POclCreateCommandQueue(cl_context, cl_device_id, cl_command_queue_properties, cl_int *) at line 42:
  |   GENERAL |  Create Command queue on device 0

    Global memory bandwidth (GBPS)
clCreateBuffer (-4)
      Tests skipped

    Single-precision compute (GFLOPS)
[2017-08-03 09:06:57.140188646481395]POCL: in fn cl_mem POclCreateBuffer(cl_context, cl_mem_flags, size_t, void *, cl_int *) at line 41:
  |   GENERAL | CL_INVALID_BUFFER_SIZE (size == 0)
clCreateBuffer (-61)
      Tests skipped

    No half precision support! Skipped

    Double-precision compute (GFLOPS)
[2017-08-03 09:06:57.93837359434445]POCL: in fn cl_mem POclCreateBuffer(cl_context, cl_mem_flags, size_t, void *, cl_int *) at line 41:
  |   GENERAL | CL_INVALID_BUFFER_SIZE (size == 0)
clCreateBuffer (-61)
      Tests skipped

    Integer compute (GIOPS)
[2017-08-03 09:06:57.913959457]POCL: in fn cl_mem POclCreateBuffer(cl_context, cl_mem_flags, size_t, void *, cl_int *) at line 41:
  |   GENERAL | CL_INVALID_BUFFER_SIZE (size == 0)
clCreateBuffer (-61)
      Tests skipped
clCreateBuffer (-4)
      Tests skipped

    Kernel launch latency : clCreateBuffer (-4)
      Tests skipped


```

**Comment by jrprice** [comment] 2017-09-03 22:01
The issue with the CUDA backend is a performance issue in the scalar evolution analysis pass in LLVM. It's been addressed in LLVM 5.0, and I can confirm that clpeak works for me using LLVM 5.0 (with a hacky workaround for #525).

**Comment by oscarbg** [comment] 2017-09-04 17:17
thanks..
nice there is some workaround for LLVM 5.0 and to know that that version fixes it..
is "that hacky workaround" somewhere to download?
also how compares then clpeak perf NV OCL driver vs POCL CUDA driver.. can post some results?

**Comment by jrprice** [comment] 2017-09-04 18:27
The workaround is to just comment out the lines that verify the module around line 105 of `lib/CL/devices/cuda/pocl-ptx-gen.cc`.

Performance compared to NVIDIA's proprietary driver looks pretty reasonable everywhere except kernel launch latency. Here's my results on a Tesla P100:
[clpeak-p100-nvcl.txt](https://github.com/pocl/pocl/files/1275328/clpeak-p100-nvcl.txt)
[clpeak-p100-pocl.txt](https://github.com/pocl/pocl/files/1275327/clpeak-p100-pocl.txt)

**Comment by pjaaskel** [comment] 2017-09-04 19:50
What is slowing the launch? Can it utilize the kernel cache properly?

**Comment by jrprice** [comment] 2017-09-04 20:48
> What is slowing the launch? Can it utilize the kernel cache properly?

I'm not really sure. If I run just the `kernel_latency` benchmark on its own the latency is fine, it only seems to be a problem when running the whole set of benchmarks together. Could just be something weird in way the we use CUDA events to generate the timestamps, but might be worth looking into.

**Comment by franz** [comment] 2017-09-05 12:43
@jrprice  @pjaaskel wild guess: could be locking overhead (either pocl cache locking, or compiler locking in pocl LLVM API code). Just a wild guess tho, really depends on how the benchmark set works.

**Comment by franz** [comment] 2017-10-18 17:08
FWIW, turns out bug is in CLpeak. I'm guessing it's some overflow somewhere, because after limiting Pocl memory with `export POCL_MEMORY_LIMIT=1`,  CLpeak works. The only remaining issue on CPU side seems to be integer test compilation taking forever.

**Comment by franz** [comment] 2018-01-19 09:29
OK, after looking into what exactly makes CLpeak compilation take forever, i've summarized my findings in [our docs.](https://github.com/pocl/pocl/blob/master/doc/sphinx/source/benchmarks.rst). This can be fixed either in LLVM (i doubt they'll be interested) or CLPeak, but not pocl. The initial comment of this bug mentions:

> large loops don't get unrolled keeping kernel compilation taking infinite time

Actually it's CLpeak doing the unrolling by recursive macros, so there's nothing we can do.

**Closed by franz** 2018-01-19 09:29 UTC
Labels: contributions welcome
