### ISSUE TITLE
pocl 1.0 fails to build on armv7

### ISSUE THREAD

**Issue by ignatenkobrain** [pocl/pocl#597] opened 2018-01-01 13:18 UTC
```c
[ 76%] Building CL to LLVM bitcode /builddir/build/BUILD/pocl-1.0/armv7hl-redhat-linux-gnueabi/lib/kernel/host/generic/vtables_fp64.cl.bc
cd /builddir/build/BUILD/pocl-1.0/armv7hl-redhat-linux-gnueabi/lib/kernel/host && /usr/bin/clang --target=armv7-unknown-linux-gnueabihf -mfloat-abi=hard -D_CL_DISABLE_LONG -mcpu=generic -emit-llvm -ffp-contract=off -Wall -Wno-unused-local-typedef -Xclang -cl-std=CL1.2 -D__OPENCL_C_VERSION__=120 -x cl -fno-stack-protector -fno-PIC -D__OPENCL_VERSION__=120 -Dcl_khr_byte_addressable_store -Dcl_khr_global_int32_base_atomics -Dcl_khr_global_int32_extended_atomics -Dcl_khr_local_int32_base_atomics -Dcl_khr_local_int32_extended_atomics -Dcl_khr_3d_image_writes -Dcl_khr_fp16 -Xclang -cl-ext=-all,+cl_khr_byte_addressable_store,+cl_khr_global_int32_base_atomics,+cl_khr_global_int32_extended_atomics,+cl_khr_local_int32_base_atomics,+cl_khr_local_int32_extended_atomics,+cl_khr_3d_image_writes,+cl_khr_fp16, -o /builddir/build/BUILD/pocl-1.0/armv7hl-redhat-linux-gnueabi/lib/kernel/host/generic/vtables_fp64.cl.bc -c /builddir/build/BUILD/pocl-1.0/lib/kernel/libclc/vtables_fp64.cl -include /builddir/build/BUILD/pocl-1.0/include/_kernel.h -include /builddir/build/BUILD/pocl-1.0/include/_enable_all_exts.h -I /builddir/build/BUILD/pocl-1.0/lib/kernel/libclc
make[2]: Leaving directory '/builddir/build/BUILD/pocl-1.0/armv7hl-redhat-linux-gnueabi'
/builddir/build/BUILD/pocl-1.0/lib/kernel/libclc/vtables_fp64.cl:1031:17: error: use of type 'double' requires cl_khr_fp64 extension to be enabled
VTABLE_FUNCTION(double, CBRT_INV_TBL, cbrt_inv_tbl);
                ^
/builddir/build/BUILD/pocl-1.0/lib/kernel/libclc/vtables_fp64.cl:1031:17: error: use of type 'double' requires cl_khr_fp64 extension to be enabled
/builddir/build/BUILD/pocl-1.0/lib/kernel/libclc/vtables_fp64.cl:1031:25: error: use of undeclared identifier 'CBRT_INV_TBL'
VTABLE_FUNCTION(double, CBRT_INV_TBL, cbrt_inv_tbl);
                        ^
/builddir/build/BUILD/pocl-1.0/lib/kernel/libclc/vtables_fp64.cl:1031:1: error: unknown type name 'double2'; did you mean 'double'?
VTABLE_FUNCTION(double, CBRT_INV_TBL, cbrt_inv_tbl);
^
/builddir/build/BUILD/pocl-1.0/lib/kernel/libclc/vtables_macros.h:31:23: note: expanded from macro 'VTABLE_FUNCTION'
     _CL_OVERLOADABLE TYPE ## 2 VTABLE_MANGLE(NAME)(uint2 idx) {   \
                      ^
<scratch space>:97:1: note: expanded from here
double2
^
/builddir/build/BUILD/pocl-1.0/lib/kernel/libclc/vtables_fp64.cl:1031:1: error: use of type 'double' requires cl_khr_fp64 extension to be enabled
/builddir/build/BUILD/pocl-1.0/lib/kernel/libclc/vtables_macros.h:31:23: note: expanded from macro 'VTABLE_FUNCTION'
     _CL_OVERLOADABLE TYPE ## 2 VTABLE_MANGLE(NAME)(uint2 idx) {   \
                      ^
<scratch space>:97:1: note: expanded from here
double2
^
/builddir/build/BUILD/pocl-1.0/lib/kernel/libclc/vtables_fp64.cl:1031:1: error: use of undeclared identifier 'double2'; did you mean 'double'?
/builddir/build/BUILD/pocl-1.0/lib/kernel/libclc/vtables_macros.h:32:9: note: expanded from macro 'VTABLE_FUNCTION'
        TYPE ## 2 retval;                        \
        ^
<scratch space>:99:1: note: expanded from here
double2
^
/builddir/build/BUILD/pocl-1.0/lib/kernel/libclc/vtables_fp64.cl:1031:1: error: use of type 'double' requires cl_khr_fp64 extension to be enabled
/builddir/build/BUILD/pocl-1.0/lib/kernel/libclc/vtables_macros.h:32:9: note: expanded from macro 'VTABLE_FUNCTION'
        TYPE ## 2 retval;                        \
        ^
<scratch space>:99:1: note: expanded from here
double2
^
/builddir/build/BUILD/pocl-1.0/lib/kernel/libclc/vtables_fp64.cl:1031:25: error: use of undeclared identifier 'CBRT_INV_TBL'
VTABLE_FUNCTION(double, CBRT_INV_TBL, cbrt_inv_tbl);
                        ^
/builddir/build/BUILD/pocl-1.0/lib/kernel/libclc/vtables_fp64.cl:1031:25: error: use of undeclared identifier 'CBRT_INV_TBL'
/builddir/build/BUILD/pocl-1.0/lib/kernel/libclc/vtables_fp64.cl:1031:1: error: unknown type name 'double3'; did you mean 'double'?
VTABLE_FUNCTION(double, CBRT_INV_TBL, cbrt_inv_tbl);
^
/builddir/build/BUILD/pocl-1.0/lib/kernel/libclc/vtables_macros.h:37:23: note: expanded from macro 'VTABLE_FUNCTION'
     _CL_OVERLOADABLE TYPE ## 3 VTABLE_MANGLE(NAME)(uint3 idx) {   \
                      ^
<scratch space>:100:1: note: expanded from here
double3
^
/builddir/build/BUILD/pocl-1.0/lib/kernel/libclc/vtables_fp64.cl:1031:1: error: use of type 'double' requires cl_khr_fp64 extension to be enabled
/builddir/build/BUILD/pocl-1.0/lib/kernel/libclc/vtables_macros.h:37:23: note: expanded from macro 'VTABLE_FUNCTION'
     _CL_OVERLOADABLE TYPE ## 3 VTABLE_MANGLE(NAME)(uint3 idx) {   \
                      ^
<scratch space>:100:1: note: expanded from here
double3
^
/builddir/build/BUILD/pocl-1.0/lib/kernel/libclc/vtables_fp64.cl:1031:1: error: use of undeclared identifier 'double3'; did you mean 'double'?
/builddir/build/BUILD/pocl-1.0/lib/kernel/libclc/vtables_macros.h:38:9: note: expanded from macro 'VTABLE_FUNCTION'
        TYPE ## 3 retval;                        \
        ^
<scratch space>:102:1: note: expanded from here
double3
^
/builddir/build/BUILD/pocl-1.0/lib/kernel/libclc/vtables_fp64.cl:1031:1: error: use of type 'double' requires cl_khr_fp64 extension to be enabled
/builddir/build/BUILD/pocl-1.0/lib/kernel/libclc/vtables_macros.h:38:9: note: expanded from macro 'VTABLE_FUNCTION'
        TYPE ## 3 retval;                        \
        ^
<scratch space>:102:1: note: expanded from here
double3
^
/builddir/build/BUILD/pocl-1.0/lib/kernel/libclc/vtables_fp64.cl:1031:25: error: use of undeclared identifier 'CBRT_INV_TBL'
VTABLE_FUNCTION(double, CBRT_INV_TBL, cbrt_inv_tbl);
                        ^
/builddir/build/BUILD/pocl-1.0/lib/kernel/libclc/vtables_fp64.cl:1031:25: error: use of undeclared identifier 'CBRT_INV_TBL'
/builddir/build/BUILD/pocl-1.0/lib/kernel/libclc/vtables_fp64.cl:1031:25: error: use of undeclared identifier 'CBRT_INV_TBL'
/builddir/build/BUILD/pocl-1.0/lib/kernel/libclc/vtables_fp64.cl:1031:1: error: unknown type name 'double4'; did you mean 'double'?
VTABLE_FUNCTION(double, CBRT_INV_TBL, cbrt_inv_tbl);
^
/builddir/build/BUILD/pocl-1.0/lib/kernel/libclc/vtables_macros.h:44:23: note: expanded from macro 'VTABLE_FUNCTION'
     _CL_OVERLOADABLE TYPE ## 4 VTABLE_MANGLE(NAME)(uint4 idx) {   \
                      ^
<scratch space>:103:1: note: expanded from here
double4
^
/builddir/build/BUILD/pocl-1.0/lib/kernel/libclc/vtables_fp64.cl:1031:1: error: use of type 'double' requires cl_khr_fp64 extension to be enabled
/builddir/build/BUILD/pocl-1.0/lib/kernel/libclc/vtables_macros.h:44:23: note: expanded from macro 'VTABLE_FUNCTION'
     _CL_OVERLOADABLE TYPE ## 4 VTABLE_MANGLE(NAME)(uint4 idx) {   \
                      ^
<scratch space>:103:1: note: expanded from here
double4
^
/builddir/build/BUILD/pocl-1.0/lib/kernel/libclc/vtables_fp64.cl:1031:1: error: use of undeclared identifier 'double4'; did you mean 'double'?
/builddir/build/BUILD/pocl-1.0/lib/kernel/libclc/vtables_macros.h:45:9: note: expanded from macro 'VTABLE_FUNCTION'
        TYPE ## 4 retval;                        \
        ^
<scratch space>:105:1: note: expanded from here
double4
^
```

**Comment by ignatenkobrain** [comment] 2018-01-01 13:21
Note that "-DCL_DISABLE_LONG=true" is passed to cmake (as you can see from `-D_CL_DISABLE_LONG` in compilation flags), but it doesn't really work.

**Comment by franz** [comment] 2018-01-03 10:03
CL_DISABLE_LONG is / was a workaround for an OpenCL bug in some ancient version of Clang, it has nothing to do with double support, and probably doesn't do anything these days. But I'll take a look

**Comment by tstellar** [comment] 2018-01-05 19:08
The problem is that there are a lot of missing #ifdef cl_khr_fp64 to guard uses of double.  sleef/ and sleef-pocl/  don't seem to do this at all.

vtables_fp64.cl just needs to move the #endif to the bottom of the file.

**Comment by franz** [comment] 2018-01-05 20:08
>  sleef/ and sleef-pocl/ don't seem to do this at all.

Not sure where you got that impression... ``sleef/`` has separate code for SP and DP, so it doesn't need guards, just disabling compilation - plus it's C not OpenCL. Currently our CMake [disables SLEEF fp64 NEON on ARM32](https://github.com/pocl/pocl/blob/master/lib/kernel/host/CMakeLists.txt#L154) but fp64 vectors are still available through fallback to VFP. WRT ``sleef-pocl/`` - most of these files are autogenerated and i see a ton of ``#ifdef cl_khr_fp64``, so perhaps there are a few forgotten but it shouldn't be too hard to fix.

> vtables_fp64.cl just needs to move the #endif to the bottom of the file.

Yep, already have a patch in queue. This fix seems to be all that's needed to compile pocl for my Cortex-A15. It's true though that i've never tried to compile on a machine which doesn't have **any** FP64 capabilities (VFP at least), there it might fail.

**Comment by franz** [comment] 2018-01-12 08:49
This should be resolved by that tiny patch; i've also removed CL_DISABLE_LONG and added ENABLE_FP64 CMake variable to disable double support completely (for ARM platform only).

**Closed by franz** 2018-01-12 08:49 UTC
Labels: ARM issue
