### ISSUE TITLE
CUDA fails with LLVM 8.0

### ISSUE THREAD

**Issue by franz** [pocl/pocl#702] opened 2019-03-18 11:41 UTC
CUDA backend seems to have one new failure with LLVM 8.0:

```
21/70 Test  #16: kernel/test_rotate ................................................................***Failed  Error regular expression found in output. Regex=[FAIL]  9.57 sec
CMake Error at /home/buildslave/basedir/quick_80_cuda/source/cmake/run_test.cmake:34 (message):
  FAIL: Test exited with nonzero code (Child aborted):
  /home/buildslave/basedir/quick_80_cuda/build/tests/kernel/kernel;test_rotate


  STDOUT:

  Running test test_rotate...

  FAIL: rotate type=

  STDERR:

  CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
```

**Comment by pjaaskel** [comment] 2019-03-18 13:18
Is this due to LLVM 8.0, that is, it works with pocl master and LLVM 7.0?

**Comment by franz** [comment] 2019-03-18 13:53
Yes, it works with git master + LLVM 7.0

**Comment by pjaaskel** [comment] 2019-03-22 22:50
@jrprice any insight?

**Comment by pjaaskel** [comment] 2019-03-25 10:54
This is possibly an LLVM regression, so we won't block pocl 1.3 due to it. If you @jrprice have time to check into it, great, but otherwise we just document it as an XFAIL.

**Comment by jrprice** [comment] 2019-03-25 11:55
I've reproduced the error on one of my machines, so I'll try and take a look soon. I agree this shouldn't block the 1.3 release.

**Comment by jrprice** [comment] 2019-04-02 13:09
I've dug into this a bit today, just recording progress here. The crash was coming from the `printf` calls - this is fixed by #707. The fact that we're getting to the `printf` calls when we weren't before still implies an LLVM regression (i.e. we're actually getting the wrong results from the `rotate` builtin). It looks like a `llvm.fshl` intrinsic was added in 8.0, so probably an issue with how this is being lowered to PTX.

**Comment by jrprice** [comment] 2019-04-02 13:47
Reported LLVM bug:
https://bugs.llvm.org/show_bug.cgi?id=41347

**Comment by pjaaskel** [comment] 2019-04-02 16:01
Thanks, so indeed an LLVM regression. I'll keep the ticket open regardless if people search for this.

**Comment by pjaaskel** [comment] 2020-09-26 07:12
It works with the latest LLVMs, so not keeping this open. If someone cares for older LLVMs+CUDA, a PR is welcome.

**Closed by pjaaskel** 2020-09-26 07:12 UTC
Labels: CUDA issue, LLVM issue
