### ISSUE TITLE
CUDA + LLVM 14

### ISSUE THREAD

**Issue by franz** [pocl/pocl#1047] opened 2022-04-18 18:28 UTC
Testing CUDA with LLVM 14 + PR for `TargetRegistry.h`, it builds but a few tests fail:

```
The following tests FAILED:
	102 - runtime/clFinish (Failed)
	110 - runtime/clSetEventCallback (Failed)
	156 - examples/scalarwave (Failed)
```

The failure seems to be the same, build log says:

```
  /home/buildslave/basedir/llvm_140_cuda/source/lib/CL/devices/cuda/pocl-cuda.c:1119:
  pocl_cuda_submit_kernel: Assertion `constant_mem_base' failed.
```

@isuruf  @jrprice  any ideas ? can you take a look ?

**Comment by isuruf** [comment] 2022-06-02 20:52
It seems that with LLVM14, the kernel
```
kernel 
void test_kernel(constant char* input) {
    if (input[0] == 'X') printf("match");
}
```
gets translated to the following PTX
```
//
// Generated by LLVM NVPTX Back-End
//

.version 6.0
.target sm_70
.address_size 64

        // .globl       test_kernel

.visible .entry test_kernel(
        .param .u32 test_kernel_param_0,
        .param .u32 test_kernel_param_1
)
{


        ret;

}
```

**Comment by isuruf** [comment] 2022-06-02 21:01
Changing https://github.com/pocl/pocl/blob/72b4fe46b14286364ff7a212242c1fd1a69c5663/lib/CL/devices/cuda/pocl-ptx-gen.cc#L647 to `OptLevel=0` fixes this. So, it seems like an LLVM bug.

**Comment by isuruf** [comment] 2022-06-02 23:06
LLVM seems to think that `vprintf` has no side-effects and optimizes the call away.

**Comment by inducer** [comment] 2022-06-07 01:08
Looks like the declaration for `vprintf` is here: https://github.com/llvm/llvm-project/blob/576b8245c838e822f709d8450f537c7909d45411/clang/lib/Headers/__clang_cuda_runtime_wrapper.h#L404=

I looked over the passes in https://github.com/llvm/llvm-project/blob/576b8245c838e822f709d8450f537c7909d45411/llvm/lib/Target/NVPTX/NVPTXTargetMachine.cpp, and none seemed particularly likely to be eliminating this call, so maybe this is happening in clang.

**Comment by isuruf** [comment] 2022-06-07 03:26
Easiest way to reproduce outside of pocl is to download https://gist.github.com/isuruf/bd39cb155f660dd980f4689cb8153cf2

```
opt --O3 -o opt.bc test-cuda-14-bug.ll
llvm-dis opt.bc
cat opt.ll
```

**Comment by isuruf** [comment] 2022-06-07 18:37
Bisected to https://github.com/llvm/llvm-project/commit/8d1759c404c7899c62d6ed89791e49b2742c1a20

**Comment by isuruf** [comment] 2022-06-08 04:50
Fixed in https://github.com/pocl/pocl/pull/1061

**Comment by isuruf** [comment] 2022-06-08 04:58
It turns out that LLVM was correct in optimizing out the call, because the constant memory region was added as internal linkage with a zero initializer as POCL converted the following to,
```
kernel 
void test_kernel(constant char* input) {
    if (input[0] == 'X') printf("match");
}
```
to
```
__constant char* _constant_memory_region_[65536] = 0;
kernel 
void test_kernel(int input_offset) {
    if (_constant_memory_region_[input_offset] == 'X') printf("match");
}
```
which LLVM optimizes away in LLVM 14.

#1061 changes this to
```
external __constant char* _constant_memory_region_[65536];
kernel 
void test_kernel(int input_offset) {
    if (_constant_memory_region_[input_offset] == 'X') printf("match");
}
```

**Closed** 2022-06-10 10:36 UTC
Labels: CUDA issue
