### ISSUE TITLE
Build failure in tests/runtime/test_clGetKernelArgInfo

### ISSUE THREAD

**Issue by patricklauer** [pocl/pocl#163] opened 2015-03-16 09:17 UTC
Trying to build pocl-0.11 on an amd64/linux (gentoo) host. Fails both with autotools and cmake in the same way:

```
[ 96%] Building C object tests/runtime/CMakeFiles/test_clGetKernelArgInfo.dir/test_clGetKernelArgInfo.c.o
cd /var/tmp/portage/dev-lang/pocl-0.11/work/pocl-0.11_build/tests/runtime && /usr/bin/x86_64-pc-linux-gnu-gcc    -DNDEBUG -O2 -pipe  -fPIE -I/var/tmp/portage/dev-lang/pocl-0.11/work/pocl-0.11_build -I/var/tmp/portage/dev-lang/pocl-0.11/work/pocl-0.11/fix-includes -I/var/tmp/portage/dev-lang/pocl-0.11/work/pocl-0.11/include    -o CMakeFiles/test_clGetKernelArgInfo.dir/test_clGetKernelArgInfo.c.o -c /var/tmp/portage/dev-lang/pocl-0.11/work/pocl-0.11/tests/runtime/test_clGetKernelArgInfo.c
Linking C executable test_clGetKernelArgInfo
cd /var/tmp/portage/dev-lang/pocl-0.11/work/pocl-0.11_build/tests/runtime && /usr/bin/cmake -E cmake_link_script CMakeFiles/test_clGetKernelArgInfo.dir/link.txt --verbose=1
/usr/bin/x86_64-pc-linux-gnu-gcc  -O2 -pipe    -Wl,-O1 -Wl,--as-needed CMakeFiles/test_clGetKernelArgInfo.dir/test_clGetKernelArgInfo.c.o  -o test_clGetKernelArgInfo -rdynamic -lm -lOpenCL ../../lib/poclu/libpoclu.so.1.4.0 -lm -lOpenCL -Wl,-rpath,/var/tmp/portage/dev-lang/pocl-0.11/work/pocl-0.11_build/lib/poclu 
CMakeFiles/test_clGetKernelArgInfo.dir/test_clGetKernelArgInfo.c.o: In function `test_program':
test_clGetKernelArgInfo.c:(.text+0xde): undefined reference to `clGetKernelArgInfo'
test_clGetKernelArgInfo.c:(.text+0x159): undefined reference to `clGetKernelArgInfo'
test_clGetKernelArgInfo.c:(.text+0x1b5): undefined reference to `clGetKernelArgInfo'
test_clGetKernelArgInfo.c:(.text+0x214): undefined reference to `clGetKernelArgInfo'
test_clGetKernelArgInfo.c:(.text+0x278): undefined reference to `clGetKernelArgInfo'
CMakeFiles/test_clGetKernelArgInfo.dir/test_clGetKernelArgInfo.c.o:test_clGetKernelArgInfo.c:(.text+0x2c3): more undefined references to `clGetKernelArgInfo' follow
collect2: error: ld returned 1 exit status
tests/runtime/CMakeFiles/test_clGetKernelArgInfo.dir/build.make:86: recipe for target 'tests/runtime/test_clGetKernelArgInfo' failed
make[2]: *** [tests/runtime/test_clGetKernelArgInfo] Error 1
make[2]: Leaving directory '/var/tmp/portage/dev-lang/pocl-0.11/work/pocl-0.11_build'
CMakeFiles/Makefile2:1917: recipe for target 'tests/runtime/CMakeFiles/test_clGetKernelArgInfo.dir/all' failed
make[1]: *** [tests/runtime/CMakeFiles/test_clGetKernelArgInfo.dir/all] Error 2
make[1]: Leaving directory '/var/tmp/portage/dev-lang/pocl-0.11/work/pocl-0.11_build'
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by kraiskil** [comment] 2015-03-16 10:02
clGetKernelArgInfo is a OpenCL extension available since OpenCL 1.2. It seems you are linking the tests against ```-lOpenCL``` (the ICD loader library), which I now guess is of OpenCL version < 1.2, e.g. the nVidia OpenCL stuff installs a 1.1 version of libOpenCL (at least they used to, last I checked).
I suggest using the ocl-icd loader https://forge.imag.fr/projects/ocl-icd/ .

**Comment by pjaaskel** [comment] 2015-03-16 15:22
http://portablecl.org/docs/html/faq.html#clreleasedevice-or-clcreateimage-missing-when-linking-against-lopencl-icd unfortunately a FAQ, we probably should add a configure check for this. ocl-icd doesn't help if its built with 1.1 headers too.

**Comment by patricklauer** [comment] 2015-03-17 03:20
Ah yes. I was accidentally using the mesa icd (ocl 1.1), with ocl-icd things work as expected.

**Comment by kraiskil** [comment] 2015-03-18 06:54
Thanks for confirming.
Closing this, as it is a duplicate of #27.

**Closed by kraiskil** 2015-03-18 06:54 UTC
