### ISSUE TITLE
./lib/llvmopencl/Kernel.cc:129: pocl::ParallelRegion* pocl::Kernel::createParallelRegionBefore(llvm::BasicBlock*): Assertion `region_entry_barrier != NULL' failed

### ISSUE THREAD

**Issue by picca** [pocl/pocl#1435] opened 2024-03-11 10:39 UTC
Hello, I am affected by this bug while preparing the Debian package of silx

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1060318

reading a bunch of your issues I found that adding

POCL_WORK_GROUP_METHOD=cbs  helps saolve the issue or at leat dos not trigger the core dump.

so my question is what is the right way to solve this  issue ?

thanks for considering

**Comment by pjaaskel** [comment] 2024-03-11 11:29
Hi. If you can create a reproducer in C/C++ with as small kernel as possible that causes it, it wold be helpful in trying to tackle the underlying problem. Meanwhile you can use the CBS for this test case.

**Comment by picca** [comment] 2024-03-11 16:42
Here some information

https://github.com/silx-kit/silx/issues/4073

It seems that this is a llvm issue...

llvm 15 ok
llvm 16 ko

**Comment by pjaaskel** [comment] 2024-03-12 12:37
And this compiles with later LLVMs, but not older than 15?

**Comment by kif** [comment] 2024-03-12 12:50
This compiles with LLVM15 and elder (as old as we remember ... the code is from 2017) but  it fails with LLVM16.

**Comment by anbe42** [comment] 2024-03-12 15:19
I bisected it to commit b165b29a251e642920a2a6ddc453b33e8d8b3e54 "LLVM 17 support", unfortunately that has
`77 files changed, 4410 insertions(+), 2341 deletions(-)`
I just rebuilt PoCL 5.0 against LLVM 17 locally and that still shows the bug.

**Comment by anbe42** [comment] 2024-03-12 19:36
minimized nonsensical kernel to reproduce the problem (reduced with cvise and some manual postprocessing)

```
__kernel void a(__local float2 *b) {
  struct {
    int c[1];
    float2 d;
  } e;
  for (int f = 0; f < 2; f++) {
    if (f)
      for (int g; g < b; g++)
        e.c[g] = 0;
    else if (b)
      e.d.s0 = b[0].s0;
    barrier(0);
  }
}
```

**Comment by pjaaskel** [comment] 2024-03-13 06:41
Thanks! Very helpful. Also a great pointer to the cvis tool - looks very useful. @franz this is likely something to do with the moving to the new PM by default? Do we still have the ability to run with the old PM to test?

**Comment by franz** [comment] 2024-03-13 11:22
Since SVMOffset pass was added without support for legacy PM, main branch does not anymore support the legacy PM.

PoCL 5.0 should be able to run with old PM, it's enough to change `MIN_LLVM_NEW_PASSMANAGER` in `config.h.in.cmake` to some higher number (this will only work up to LLVM 16).

**Comment by pjaaskel** [comment] 2024-03-13 12:07
The SVMOffset pass is not used in the client-side kernel compilation pipeline, but only called from command line from the pocld server side, so it shouldn't affect this.

**Comment by franz** [comment] 2024-04-04 17:39
@picca @kif - could any of you test the "real" kernel in silx with [this branch](https://github.com/franz/pocl/tree/fix_1435) - it should fix the crash, but i'm interested if it produces correct results.

**Comment by kif** [comment] 2024-04-05 16:02
Hi Michal,

I tested the default ICD (probaly the nvidia one):
```
(py311) lintaillefer:~/workspace/silx % ./run_tests.py src/silx/image/test/test_medianfilter.py
INFO:silx.setup:Install requires: numpy >=1.26.4
Building silx to /users/kieffer/workspace-400/silx/build/lib.linux-x86_64-3.11
INFO:silx.setup:Install requires: numpy >=1.26.4
running build
running build_py
running build_ext
INFO: Disabling color, you really want to install colorlog.
INFO:pythran:Disabling color, you really want to install colorlog.
Patched sys.path, added: '/users/kieffer/workspace-400/silx/build/lib.linux-x86_64-3.11'
==================================================================================== test session starts =====================================================================================
platform linux -- Python 3.11.0, pytest-7.2.2, pluggy-1.0.0
rootdir: /users/kieffer/workspace-400/silx/build/lib.linux-x86_64-3.11/silx, configfile: ../../../pytest.ini
plugins: anyio-3.7.1, xvfb-2.0.0
collected 2 items                                                                                                                                                                            

build/lib.linux-x86_64-3.11/silx/image/test/test_medianfilter.py ..                                                                                                                    [100%]

===================================================================================== 2 passed in 0.46s ======================================================================================
```

Then the POCL v5 which is known to crash the process:
```
(py311) lintaillefer:~/workspace/silx % OCL_ICD_VENDORS=/opt/pocl5/etc/OpenCL/vendors/pocl.icd ./run_tests.py src/silx/image/test/test_medianfilter.py
INFO:silx.setup:Install requires: numpy >=1.26.4
Building silx to /users/kieffer/workspace-400/silx/build/lib.linux-x86_64-3.11
INFO:silx.setup:Install requires: numpy >=1.26.4
running build
running build_py
running build_ext
INFO: Disabling color, you really want to install colorlog.
INFO:pythran:Disabling color, you really want to install colorlog.
Patched sys.path, added: '/users/kieffer/workspace-400/silx/build/lib.linux-x86_64-3.11'
==================================================================================== test session starts =====================================================================================
platform linux -- Python 3.11.0, pytest-7.2.2, pluggy-1.0.0
rootdir: /users/kieffer/workspace-400/silx/build/lib.linux-x86_64-3.11/silx, configfile: ../../../pytest.ini
plugins: anyio-3.7.1, xvfb-2.0.0
collected 2 items                                                                                                                                                                            

build/lib.linux-x86_64-3.11/silx/image/test/test_medianfilter.py .  [crashed here]
```

And finally the patched version from branch fix 1435:
```
(py311) lintaillefer:~/workspace/silx % OCL_ICD_VENDORS=/opt/pocl6/etc/OpenCL/vendors/pocl.icd ./run_tests.py src/silx/image/test/test_medianfilter.py
INFO:silx.setup:Install requires: numpy >=1.26.4
Building silx to /users/kieffer/workspace-400/silx/build/lib.linux-x86_64-3.11
INFO:silx.setup:Install requires: numpy >=1.26.4
running build
running build_py
running build_ext
INFO: Disabling color, you really want to install colorlog.
INFO:pythran:Disabling color, you really want to install colorlog.
Patched sys.path, added: '/users/kieffer/workspace-400/silx/build/lib.linux-x86_64-3.11'
==================================================================================== test session starts =====================================================================================
platform linux -- Python 3.11.0, pytest-7.2.2, pluggy-1.0.0
rootdir: /users/kieffer/workspace-400/silx/build/lib.linux-x86_64-3.11/silx, configfile: ../../../pytest.ini
plugins: anyio-3.7.1, xvfb-2.0.0
collected 2 items                                                                                                                                                                            

build/lib.linux-x86_64-3.11/silx/image/test/test_medianfilter.py ..                                                                                                                    [100%]

===================================================================================== 2 passed in 0.13s ======================================================================================
```

So apparently the results look good.

Thanks for the patch. It looks like it fixes the issue.

-- 
Jérôme Kieffer

**Comment by franz** [comment] 2024-04-16 10:09
fixed in main branch

**Closed by franz** 2024-04-16 10:09 UTC
Labels: Kernel compiler, Regression
