### ISSUE TITLE
hwloc 2 support

### ISSUE THREAD

**Issue by sthibaul** [pocl/pocl#545] opened 2017-10-27 11:38 UTC
Hello,

hwloc 2 is to be released sooner or later, and it introduces a few API changes. The build log for version 0.13 of pocl shows:

`
pocl_topology.c:51:43: error: 'HWLOC_TOPOLOGY_FLAG_WHOLE_IO' undeclared (first use in this function); did you mean 'HWLOC_TOPOLOGY_FLAG_WHOLE_SYSTEM'?
   hwloc_topology_set_flags(pocl_topology, HWLOC_TOPOLOGY_FLAG_WHOLE_IO);
                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                           HWLOC_TOPOLOGY_FLAG_WHOLE_SYSTEM
`

There might also be other issues.

To test against the development tree for hwloc 2, one can use

`git clone http://github.com/open-mpi/hwloc.git`

Samuel

**Comment by pjaaskel** [comment] 2017-10-27 12:58
Dupe of #358

**Closed by pjaaskel** 2017-10-27 12:58 UTC
Labels: duplicate
