### ISSUE TITLE
vector types larger than a cpu vector register don't get passed to printf

### ISSUE THREAD

**Issue by anbe42** [pocl/pocl#1017] opened 2021-12-09 01:07 UTC
Hi,

I've been debugging the printf issues a bit further, looking at `ulong16` failing where `ulong2` succeeds.
The issue I'm describing here happens on `x86_64` and is not a bug in the printf implementation, but happens earlier: while passing the arguments to the printf call.
A new test kernel `test_printf_vectors_ulongn.cl` for inspecting the assembly is part of my cleanup-tests branch.

I've built with `LLC_HOST_CPU=haswell` and will only look at `ulong4` (fits into a 256-bit vector register `ymm#`) and `ulong8` (does not fit into a single vector register). Look at the disassembly yourself for other types. (For other targets the results are similar, e.g. `x86-64`: only `ulong2` fits into a `xmm#` register or `skylake-avx512`: up to `ulong8` does fit into an `xmm#`, `ymm#` or `zmm#` register, but `ulong16` does not fit anywhere.)

The difference in the output:
```
 ulong4   0xe1e2e3e4e5e6e7e8,0xe9eaebecedeeeff1,0xf2f3f4f5f6f7f8f9,0xfafbfcfdfeff1112
-ulong8   0x2122232425262728,0x292a2b2c2d2e2f31,0x3233343536373839,0x3a3b3c3d3e3f4142,0x434445464748494a,0x4b4c4d4e4f515253,0x5455565758595a5b,0x5c5d5e5f61626364
+ulong8   0xe1e2e3e4e5e6e7e8,0xe9eaebecedeeeff1,0xf2f3f4f5f6f7f8f9,0xfafbfcfdfeff1112,0x656b5f6c636f705f,0x7365745f6c656e72,0x66746e6972705f74,0x73726f746365765f
```

```
int pl4() __attribute__((noinline));
int pl4()
{
  printf("ulong4   %#v4lx\n", (ulong4)(0xe1e2e3e4e5e6e7e8UL, 0xe9eaebecedeeeff1UL,
                                       0xf2f3f4f5f6f7f8f9UL, 0xfafbfcfdfeff1112UL));
  return 0;
}
```
```
0000000000004ac0 <pl4>:
    4ac0:       55                      push   %rbp
    4ac1:       48 89 e5                mov    %rsp,%rbp
    4ac4:       48 83 e4 e0             and    $0xffffffffffffffe0,%rsp
    4ac8:       48 83 ec 40             sub    $0x40,%rsp
    4acc:       c5 fc 28 05 0c 06 00    vmovaps 0x60c(%rip),%ymm0        # 50e0 <ulong4 value>
    4ad3:       00
    4ad4:       c5 fc 29 04 24          vmovaps %ymm0,(%rsp)
    4ad9:       48 8d 0d 52 0b 00 00    lea    0xb52(%rip),%rcx        # 5632 <format string>
    4ae0:       31 c0                   xor    %eax,%eax
    4ae2:       c5 f8 77                vzeroupper
    4ae5:       e8 66 f7 ff ff          call   4250 <__pocl_printf>
    4aea:       48 89 ec                mov    %rbp,%rsp
    4aed:       5d                      pop    %rbp
    4aee:       c3                      ret

```
The `ulong4` argument is passed on the stack.

```
int pl8() __attribute__((noinline));
int pl8()
{
  printf("ulong8   %#v8lx\n", (ulong8)(0x2122232425262728UL, 0x292a2b2c2d2e2f31UL,
                                       0x3233343536373839UL, 0x3a3b3c3d3e3f4142UL,
                                       0x434445464748494aUL, 0x4b4c4d4e4f515253UL,
                                       0x5455565758595a5bUL, 0x5c5d5e5f61626364UL));
  return 0;
}
```
```
0000000000004af0 <pl8>:
    4af0:       55                      push   %rbp
    4af1:       48 89 e5                mov    %rsp,%rbp
    4af4:       48 83 e4 c0             and    $0xffffffffffffffc0,%rsp
    4af8:       48 81 ec 80 00 00 00    sub    $0x80,%rsp
    4aff:       48 8d 0d 3d 0b 00 00    lea    0xb3d(%rip),%rcx        # 5643 <format string>
    4b06:       49 89 e0                mov    %rsp,%r8
    4b09:       31 c0                   xor    %eax,%eax
    4b0b:       e8 40 f7 ff ff          call   4250 <__pocl_printf>
    4b10:       48 89 ec                mov    %rbp,%rsp
    4b13:       5d                      pop    %rbp
    4b14:       c3                      ret
```
Big difference: the `ulong8` argument is not loaded/created at all, so printf output some random data from the stack...

Passing `ulong8` to a non-variadic function works fine:
```
ulong f8(ulong8 ul8, ulong z) __attribute__((noinline));
ulong g8() __attribute__((noinline));
ulong g8()
{
ulong8 ul8 = (ulong8)(0x18, 0x29, 0x3a, 0x4b, 0x5c, 0x6d, 0x7e, 0x8f);
return -f8(ul8, 0x123456789abcdef1UL);
}
```
```
00000000000044b0 <g8>:
    44b0:       55                      push   %rbp
    44b1:       48 89 e5                mov    %rsp,%rbp
    44b4:       48 83 e4 f0             and    $0xfffffffffffffff0,%rsp
    44b8:       c5 fc 28 05 80 0b 00    vmovaps 0xb80(%rip),%ymm0        # 5040 <ulong8 value>
    44bf:       00
    44c0:       c5 fc 28 0d 98 0b 00    vmovaps 0xb98(%rip),%ymm1        # 5060 <ulong8 value continued>
    44c7:       00
    44c8:       48 bf f1 de bc 9a 78    movabs $0x123456789abcdef1,%rdi
    44cf:       56 34 12
    44d2:       e8 d9 fe ff ff          call   43b0 <f8>
    44d7:       48 f7 d8                neg    %rax
    44da:       48 89 ec                mov    %rbp,%rsp
    44dd:       5d                      pop    %rbp
    44de:       c5 f8 77                vzeroupper
    44e1:       c3                      ret
```
The `ulong8` argument gets passed in 2 registers `ymm0`, `ymm1`.

Compiling the OpenCL kernel directly with clang-13 (without pocl at all):
`clang-13 -x cl -c -O2 -mavx  ../tests/kernel/test_printf_vectors_ulongn.cl -o ulongn.o`
```
0000000000000300 <pl8>:
 300:   55                      push   %rbp
 301:   48 89 e5                mov    %rsp,%rbp
 304:   48 83 e4 c0             and    $0xffffffffffffffc0,%rsp
 308:   48 81 ec c0 00 00 00    sub    $0xc0,%rsp
 30f:   c5 fc 28 05 00 00 00    vmovaps 0x0(%rip),%ymm0        # 317 <pl8+0x17>
 316:   00
 317:   c5 fc 29 44 24 60       vmovaps %ymm0,0x60(%rsp)
 31d:   c5 fc 28 05 00 00 00    vmovaps 0x0(%rip),%ymm0        # 325 <pl8+0x25>
 324:   00
 325:   c5 fc 29 44 24 40       vmovaps %ymm0,0x40(%rsp)
 32b:   c5 fc 28 44 24 40       vmovaps 0x40(%rsp),%ymm0
 331:   c5 fc 28 4c 24 60       vmovaps 0x60(%rsp),%ymm1
 337:   c5 fc 29 4c 24 20       vmovaps %ymm1,0x20(%rsp)
 33d:   c5 fc 29 04 24          vmovaps %ymm0,(%rsp)
 342:   bf 00 00 00 00          mov    $0x0,%edi
 347:   31 c0                   xor    %eax,%eax
 349:   c5 f8 77                vzeroupper
 34c:   e8 00 00 00 00          call   351 <pl8+0x51>
 351:   31 c0                   xor    %eax,%eax
 353:   48 89 ec                mov    %rbp,%rsp
 356:   5d                      pop    %rbp
 357:   c3                      ret
```
The call abi seems to be different, but the `ulong8` value gets passed on the stack.

So here I think the pocl specific llvm passes cause this problem.
I hope this analysis helps you to continue debugging...

**Comment by pjaaskel** [comment] 2023-04-17 16:18
Can you create a PoCL test case of this (with XFAILs as applicable) so we can more easily track it with later LLVMs? Quickly I cannot see which PoCL passes would do anything here, but who knows.

**Comment by franz** [comment] 2023-10-13 14:48
Related issue: SPIR-V input fails certain vector types. E.g. this kernel (one of CTS printf tests):

```
__kernel void test10(void)
{
  ushort2 tmp = (ushort2)(0x1234,0x8765);
  printf("%#v2hx\n",tmp);
}
```

when compiled from C source directly to x86-64 target, results in this LLVM IR: 

```
define dso_local spir_kernel void @test10() local_unnamed_addr #0 !kernel_arg_addr_space !5 !kernel_arg_access_qual !5 !kernel_arg_type !5 !kernel_arg_base_type !5 !kernel_arg_type_qual !5 >
entry:
  %fmt_str_cast = addrspacecast ptr @.str to ptr addrspace(2)
  %call = tail call i32 (ptr addrspace(2), ...) @printf(ptr addrspace(2) noundef nonnull %fmt_str_cast, i32 noundef -2023419340) #14
  ret void
}
```

which correctly prints the vector. However compiling the source for SPIR-V target results in this LLVM IR:

```
; Function Attrs: nounwind
define spir_kernel void @test10() #0 !kernel_arg_addr_space !5 !kernel_arg_access_qual !5 !kernel_arg_type !5 !kernel_arg_type_qual !5 !kernel_arg_base_type !5 {
entry:
  %0 = getelementptr inbounds [8 x i8], ptr addrspace(2) @.str, i64 0, i64 0
  %call = call i32 (ptr addrspace(2), ...) @printf(ptr addrspace(2) %0, <2 x i16> <i16 4660, i16 -30875>) #0
  ret void
}
```

and this one fails to print the correct values. The problem is that the current implementation of `printf()` uses `va_start/va_end` to process variadic args, this is target-ABI dependent. I'm not sure there is any other way to solve this than a custom LLVM pass.

**Comment by franz** [comment] 2024-09-25 14:43
This should be now fixed in main branch. Reopen if you believe it's not

**Closed by franz** 2024-09-25 14:43 UTC
