### ISSUE TITLE
POCL NBody speed regression

### ISSUE THREAD

**Issue by franz** [pocl/pocl#251] opened 2015-10-06 13:59 UTC
Testing Pocl with various LLVM versions, the NBody test from AMD SDK samples seems to have become considerably slower:
```
./Nbody -t -x 19968 -q -i 10
```
LLVM | time (sec)
--------- | --------
3.5      | 1.128
3.6      | 1.275
3.7      | 2.19  

The 3.7 result is now worse than AMD SDK 3.0 (which is 1.29 sec)

**Comment by eschnett** [comment] 2015-10-06 15:01
Without having looked at the details: The Julia language experience a slow-down when moving to LLVM 3.7; the reason there was that the pass manager changed, and a pass was missing. This stopped the auto-vectorizer from working. https://github.com/JuliaLang/julia/issues/13106

**Comment by pjaaskel** [comment] 2015-10-06 15:09
https://github.com/pocl/pocl/blob/master/lib/CL/pocl_llvm_api.cc#L1013 it's done there. Autovec seems to work, I just tried the smoke test of example1.  I'm suspecting the parallel loop metadata format now.

**Comment by pjaaskel** [comment] 2015-10-06 15:29
Seems to be OK. POCL_VECTORIZER_REMARKS could be useful here.

**Comment by pjaaskel** [comment] 2015-10-06 15:45
I see it calling the libm sqrtf() which probably prevents/prevented vectorization and other optimizations. I wonder if that's the reason?

```LLVM
 ...
  %add11.i.prol = fadd float %mul10.i.prol, %add9.i.prol
  %add12.i.prol = fadd float %add11.i.prol, %4
  %call.i.1.i.prol = tail call float @sqrtf(float %add12.i.prol) #4
  %div.i.prol = fdiv float 1.000000e+00, %call.i.1.i.prol, !fpmath !7
  %mul14.i.prol = fmul float %div.i.prol, %div.i.prol
  ...
```

**Comment by pjaaskel** [comment] 2015-10-06 15:57
Seems to be there also when built with LLVM 3.6.

**Comment by pjaaskel** [comment] 2015-10-06 16:05
OK. Found the reason: BBVectorizer disabled for LLVM 3.7 due to a regression. With it enabled, it gets down to about 1.3s. I'll see if the regression is gone (all tests pass) and push if so.

**Comment by pjaaskel** [comment] 2015-10-06 16:49
The shuffle test regression is not gone, it still crashes. I reported it to LLVM:  https://llvm.org/bugs/show_bug.cgi?id=25077  we might need to add yet another pocl env to control this and disable by default.

**Closed** 2015-10-07 07:51 UTC
