### ISSUE TITLE
SIGSEGV (miscompiling the kernel?)

### ISSUE THREAD

**Issue by dizcza** [pocl/pocl#926] opened 2021-02-16 20:34 UTC
Originally posted in https://github.com/conda-forge/pocl-feedstock/issues/60

-----------------

POCL v1.6 anaconda backend is unstable with PyOpenCL 2021.1. The issue appears only in POCL (intel-compute-runtime and oclgrind anaconda backends do not have this issue), therefore it's a problem in POCL (or how it interacts with PyOpenCL).

Installed with `conda install -c conda-forge pyopencl pocl`. Python v3.9

```python
import numpy as np
import pyopencl as cl
import pyopencl.array as cl_array

ctx = cl.create_some_context()
dev = ctx.devices[0]
print(dev)
queue = cl.CommandQueue(ctx)

arr = cl_array.zeros(queue, shape=2, dtype=np.float32)
output = cl_array.Array(queue, shape=1, dtype=np.float32)

with open("kernel.cl") as f:
    kernel_str = f.read()

program = cl.Program(ctx, kernel_str).build()

# synchronize
cl.enqueue_barrier(queue)

kernel = program.jsf_uniform_orderstat_3d_kernel
grid_size = 1
n_threads = 2
kernel(queue, (grid_size,), (n_threads,), output.data, arr.data, g_times_l=True)

print(output.get())
```

The output:
```
<pyopencl.Device 'pthread-Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz' on 'Portable Computing Language' at 0x55b786124e60>

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```

Kernel:
```c

__kernel void jsf_uniform_orderstat_3d_kernel(__global float *P_out, __global const float *log_du_device) {
    unsigned int i;
    unsigned long row;

    const int threadIdx_x = get_local_id(0);
    const int blockDim_x = get_local_size(0);

    __local float log_du[2];

    for (row = threadIdx_x; row < 1; row += blockDim_x) {
        for (i = 0; i < 2; i++) {
            log_du[i] = log_du_device[i];
        }
    }

    barrier(CLK_LOCAL_MEM_FENCE);

    float colsum = 0;
    colsum += log_du[0];

    P_out[0] = 1;
}
```

Expected output: the program prints `[1.]` after the kernel has been executed.

See [inducer's response](https://github.com/conda-forge/pocl-feedstock/issues/60#issuecomment-780071172) in the original issue for an in-depth look.

**Comment by diegoxfx** [comment] 2021-02-17 12:15
@pjaaskel I think my problem (#925) is related with this. By the way, I also got the "fatal error: malformed or corrupted AST file" when trying to run my kernel with oclgrind.

**Comment by pjaaskel** [comment] 2021-02-17 12:32
This is interesting, and now it rings the bell also for #895 (@jrprice note). Is this a new bug, and has worked before? If so, can you bisect? Thanks.

**Comment by franz** [comment] 2021-10-05 09:56
Tested with PoCL 1.8 branch, LLVM 13, PyOpenCL 2021.2.6, Python 3.8, Ubuntu 20.04 LTS on two machines, AMD & Intel, cannot reproduce. @dizcza can you retest with 1.8 ?

**Comment by dizcza** [comment] 2021-10-05 13:07
@franz 
If the issue is not reproducible, feel free to close it. Conda POCL release 1.8 is not available for an easy check, and I'm not using POCL at the moment, so it's inconvenient for me to set up the whole system just to test whether the bug has been fixed.

**Comment by franz** [comment] 2021-10-05 20:35
OK closing, if the bug still exists we can reopen it.

**Closed by franz** 2021-10-05 20:35 UTC
Labels: needs more info
