### ISSUE TITLE
Testsuite fails with pocl-0.11 and llvm-3.6

### ISSUE THREAD

**Issue by fabiand** [pocl/pocl#181] opened 2015-04-13 19:27 UTC
The testsuite fails on Fedora Rawhide (23) with llvm 3.6:

```
 20: Kernel functions abs abs_diff add_sat hadd mad_hi mad_sat mul_hi rhadd sub_sat (loopvec) ok
 21: Kernel functions abs abs_diff add_sat hadd mad_hi mad_sat mul_hi rhadd sub_sat (loops) ok
 22: Kernel functions << >> rotate                   ok
 23: Trigonometric functions                         ok
 24: Sampler address clamp                           FAILED (testsuite.at:264)
 25: Image query functions                           FAILED (testsuite.at:272)
 26: Kernel functions: shuffle charN                 ok
 27: Kernel functions: shuffle shortN                ok
```

**Comment by fabiand** [comment] 2015-04-13 19:28
The whole log is available http://fpaste.org/210445/42895330/

**Comment by besser82** [comment] 2015-04-13 19:32
Full build logs are [available on Koji](https://koji.fedoraproject.org/koji/taskinfo?taskID=9454480).

**Comment by pjaaskel** [comment] 2015-04-14 06:51
I testsuite.log or better the individual logs in testsuite.dir/{24,25} somewhere? Is the Rawhide's LLVM standard or some SVN revision?

**Comment by besser82** [comment] 2015-04-14 09:51
LLVM in Rawhide is from released 3.6.0-tarball, no scm-snapshot or something…

Here goes the individual logs:
* [test log from 24](http://paste.fedoraproject.org/210713/42900490)
* [test log from 25](http://paste.fedoraproject.org/210714/14290049)

Here goes the complete [testsuite.log](http://paste.fedoraproject.org/210717/90050441).

**Comment by pjaaskel** [comment] 2015-04-14 15:16
Have you tried the latest pocl master? I think there was some work on images recently which might have fixed this.

**Comment by cjacker** [comment] 2015-07-25 11:36
get_image_width/height... failed with llvm/clang 3.6.0/3.6.1/3.6.2/3.7.0rc1.

**Comment by pjaaskel** [comment] 2015-09-25 12:18
Not a regression (if broken also in 0.11) and hard to reproduce. Found a system where these two tests fail, but don't know why.

**Comment by pjaaskel** [comment] 2015-09-25 12:20
...and that system got fixed with a clean build too.

**Comment by gerddie** [comment] 2015-10-14 16:25
I hit the same error when compiling the version 0.11 within a virtual machine running Debian/sid, target x86_64. llvm an clang versions are 3.6.2. 

The build configuration can be obtained from 

    git://anonscm.debian.org/collab-maint/pocl.git

**Comment by gerddie** [comment] 2015-10-14 22:32
I tested git head compiling by just running ./autoge.sh && ./configure  without special arguments. 

* in the virtual machine with llvm-3.7 15 tests fail (1 expected). The two in question here give: 

    Running test test_sampler_address_clamp...
    +in bounds read failed
    +got: 0 65280 0 0
    +in bounds read failed
    +out of bounds read failed
    +out of bounds read failed
    +out of bounds read failed
    +out of bounds read failed

    Running test test_image_query_funcs...
    +get_image_height failed expected 4, got 16843009
    +get_image_width failed expected 2, got 16843009
    +get_image_width failed expected 8, got 16843009
    +get_image_height failed expected 4, got 16843009
    +get_image_width failed expected 2, got 16843009

The other tests that failed within the virtual machine report:  

* 009: error: Explicit load/store type does not match pointee type of pointer operand
* 016, 021, 032, 033, 034: error: Invalid record
* 011, 020, 022, 023, 024, 028: Segmentation fault 

The same code run directly on the metal within a Gentoo installation and also llvm-3.7 results in all tests passing. 

For the hardware _configure_ reports 

    architecture: x86_64
    cpu variant: btver1

within the virtual machine, and 

    architecture: x86_64
    cpu variant: btver2

outside. The actual processor is an AMD FX(tm)-6300, but within the virtual machine a lot less cpu flags are reported, e.g. missing are  _fma_ _sse4_1_, _sse4_2_

**Comment by gerddie** [comment] 2015-10-15 19:46
Now, Ive tested the code also on Debian/sid amd64  compiled with llvm-3.7 on 

    architecture: x86_64
    cpu variant: penryn

Here, the tests _sampler_address_clamp_ and _image_query_funcs_ fail like above. In addition test 110 fails with 
    
    Assertion: 
    found_cus[0] == 1 && found_cus[1] == 1
    failed on test_clCreateSubDevices.c:339

Also,  when running the tests on Debian/sid amd64, architecture: x86_64, cpu variant: btver2, (i.e. the same hardware like above Gentoo system) all tests pass.

All tests were run with 54b4a66

**Comment by pjaaskel** [comment] 2015-10-16 05:54
Is this with 0.12rc1? Please note that we don't have anyone maintaining older releases at the moment.

**Comment by pjaaskel** [comment] 2015-10-16 06:55
Oh, sorry you said 54b4a66

**Comment by cjacker** [comment] 2015-10-28 00:52
There two failure still exist with llvm/clang-3.7.1 svn 251274, glibc-2.22, pocl git master (native build, not vm), with llvm CPU detection fixed(It not affect this CPU type acctually)

### clang -v:
clang version 3.7.0 (branches/release_37 251274) (based on LLVM 3.7.0)
Target: x86_64-isoft-linux
Thread model: posix
Found candidate GCC installation: /usr/lib/gcc/x86_64-isoft-linux/5.2.0
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-isoft-linux/5.2.0
Candidate multilib: .;@m64
Selected multilib: .;@m64


### llc --version:
LLVM (http://llvm.org/):
  LLVM version 3.7.0
  DEBUG build.
  Built Oct 26 2015 (23:54:17).
  Host CPU: broadwell

### clinfo:
Number of platforms                               3
  Platform Name                                   Intel Gen OCL Driver
  Platform Vendor                                 Intel
  Platform Version                                OpenCL 1.2 beignet 1.2 (git-5db1ac3)
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_image2d_from_buffer cl_khr_spir cl_khr_icd
  Platform Extensions function suffix             Intel

  Platform Name                                   Portable Computing Language
  Platform Vendor                                 The pocl project
  Platform Version                                OpenCL 1.2 pocl 0.13-pre
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd
  Platform Extensions function suffix             POCL

  Platform Name                                   Clover
  Platform Vendor                                 Mesa
  Platform Version                                OpenCL 1.1 MESA 11.1.0-devel
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd
  Platform Extensions function suffix             MESA

### llvm configuration:
    -G Ninja \
    -DCMAKE_C_COMPILER=clang \
    -DCMAKE_CXX_COMPILER=clang++ \
    -DCMAKE_BUILD_TYPE="Release" \
    -DCMAKE_C_FLAGS="-fPIC" \
    -DCMAKE_CXX_FLAGS="-std=c++11 -fPIC" \
    -DLLVM_ENABLE_EH=ON \
    -DLLVM_ENABLE_RTTI=ON \
    -DBUILD_SHARED_LIBS=ON \
    -DLLVM_ENABLE_PIC=ON \
    -DLLVM_TARGETS_TO_BUILD="all"

### pocl configuration:
export LLC_HOST_CPU="x86-64"
./configure

### details:
1, If no OpenCL implementation installed, aka, no beignet, no pocl. Pocl will pass all tests except these two.
That's ok, since these two test failed to clCreateContextType.

2, After installed beignet, these two test will pass.
that means beignet works.

3, After install pocl, and use POCL as default OpenCL platform, these two test failed. like before.

**Closed** 2015-10-31 19:17 UTC
