### ISSUE TITLE
OpenCL conformance test_event_other will hang with basic device

### ISSUE THREAD

**Issue by BeMg** [pocl/pocl#942] opened 2021-05-13 07:52 UTC
I run the conformance test with the following setting 

LLVM 12 + PoCL 1.7 + basic device 
 
but the test_event_other doesn't end. 

In pthread device, this test case works normally.

**Comment by pjaaskel** [comment] 2021-05-13 08:01
Does it work with older LLVM 11 (I doubt) or older PoCL? basic device isn't tested as much as pthread, so this is not surprising. We should test it more, but if this is not a regression, it won't hold back the 1.7 release.

**Comment by pjaaskel** [comment] 2023-04-17 14:10
#1177 is a duplicate of this and has more info.

**Closed by pjaaskel** 2023-04-17 14:10 UTC
